# Generated by Django 4.2.6 on 2023-10-06 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Description"),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["issue"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Nom du problème"),
                ),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_DO", "to_do"),
                            ("IN_PROGRESS", "in_progress"),
                            ("FINISHED", "finished"),
                        ],
                        default="A_faire",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "low"),
                            ("MEDIUM", "medium"),
                            ("HIGH", "high"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("BUG", "bug"),
                            ("FEATURE", "feature"),
                            ("TASK", "task"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["project"],
            },
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="project",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
    ]
