# Generated by Django 4.2.5 on 2023-09-14 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Nom du problème"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A faire", "To Do"),
                            ("En cours", "In Progress"),
                            ("Terminé", "Finished"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Basse", "Low"),
                            ("Moyenne", "Medium"),
                            ("Haute", "High"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("Bug", "Bug"),
                            ("Fonctionnalité", "Feature"),
                            ("Tâche", "Task"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_assigned_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attribué à ",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                related_name="projets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contributeurs",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.DeleteModel(
            name="Contributor",
        ),
        migrations.AddField(
            model_name="issue",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Issues",
                to="project.project",
            ),
        ),
    ]
