# Generated by Django 4.2.5 on 2023-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_comment_issue_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Basse"), ("MEDIUM", "Moyenne"), ("HIGH", "Haute")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("BUG", "Bug"),
                    ("FEATURE", "Fonctionnalité"),
                    ("TASK", "Tâche"),
                ],
                max_length=15,
            ),
        ),
    ]
