# Generated by Django 4.2.5 on 2023-09-18 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0002_alter_project_options_alter_contributor_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
