# Generated by Django 4.2.5 on 2023-09-22 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0002_comment_issue_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                db_table="Contributorr",
                null=True,
                related_name="contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
