# Generated by Django 4.2.5 on 2023-09-14 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_issue_alter_project_options_project_contributors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="projet",
            new_name="project",
        ),
    ]
