# Generated by Django 4.2.5 on 2023-09-14 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_issue_project_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["issue"]},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["project"]},
        ),
    ]
