# Generated by Django 4.2.5 on 2023-09-14 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_alter_issue_assigned_to_alter_issue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                default="user.User",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
    ]
