# Generated by Django 4.2.5 on 2023-09-18 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_contributor_unique_together"),
        ("project", "0007_alter_comment_author"),
    ]

    operations = []
