# Generated by Django 4.2.5 on 2023-10-06 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(15)]
            ),
        ),
    ]
